### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hanyu586** [96chh/crawl-zsxq#12]
Traceback (most recent call last):
  File "C:/Users/Administrator/Downloads/crawl-zsxq-master/crawl.py", line 119, in <module>
    make_pdf(get_data(start_url))
  File "C:/Users/Administrator/Downloads/crawl-zsxq-master/crawl.py", line 37, in get_data
    for topic in json.loads(f.read()).get('resp_data').get('topics'):
TypeError: 'NoneType' object is not iterable
提示这个错误怎么解决呢？

**Comment by d8899p** [comment]
TypeError: 'NoneType' object is not iterable
我也是出现这个问题，请问怎么解决的

**Comment by Timzhouyes** [comment]
> TypeError: 'NoneType' object is not iterable
> 我也是出现这个问题，请问怎么解决的

我这边解决了这个问题，是因为cookie格式不对，在下面找Cookie关键字直接替换成浏览器cookie就好。

**Comment by jason-huanghao** [comment]
希望这截图能解决大部分问题
<img width="620" alt="image" src="https://user-images.githubusercontent.com/73536129/229333335-7a184be1-8192-49f2-8cc3-2ab4f71126bc.png">
